name: fit_points
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  # Localización e internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Iconos iOS
  cupertino_icons: ^1.0.8

  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.1

  pedometer: ^4.0.1         # usa la última versión que veas en pub.dev
  permission_handler: ^11.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/rutinas.json
    - assets/

